# Generated by Django 6.0.3 on 2026-04-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
