# Generated by Django 6.0.3 on 2026-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
